- name: Install mysql database deployment
  hosts: backend
  become: yes
  vars_files:
    - group_vars/all.yml      # ğŸ” Encrypted vars
    - group_vars/vault.yml      # ğŸ” Encrypted vars   
  roles:
    - role: mysql